name: mindvault
description: ""
publish_to: 'none'

# app bundle version
version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Temel
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.5


#new 29.04
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.0.0
  flutter_markdown: ^0.7.7
  material_tag_editor: ^0.1.2
  collection: ^1.18.0
  speech_to_text: ^7.0.0
  stacked_themes: ^0.3.15
  font_awesome_flutter: ^10.8.0

  #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.15.0
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4

  uuid: ^4.5.1

  flutter_launcher_icons: ^0.14.3


  # Arayüz
  flutter_card_swiper: ^7.0.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2

  # Veri İşleme
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Dil ve Yapay Zeka
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  intl: 0.19.0
  google_generative_ai: ^0.4.6
  logger: ^1.3.0
  path_provider: ^2.1.5

  # BLOC Pattern ve State Yönetimi
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  share_plus: ^10.1.4

  #purchase
  in_app_purchase: ^3.2.1

  permission_handler: ^11.4.0
  audioplayers: ^6.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_app_check: ^0.3.2+4

  flutter_native_splash: ^2.4.0

  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^2.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pages/
    - assets/pages/light/
    - assets/pages/leather/
    - assets/pages/dark/
    - assets/pages/antique/
    - assets/pages/watercolor/
    - assets/pages/japanase_minimalist/
    - assets/pages/digital_scrapbooking/
    - assets/pages/architectural_blueprint_style/


  # Jenerik L10n
  generate: true
flutter_intl:
  enabled: true

